//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeReminder.Models.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReminderDBEntities : DbContext
    {
        public ReminderDBEntities()
            : base("name=ReminderDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserReminder> UserReminders { get; set; }
        public virtual DbSet<User> Users { get; set; }

        public System.Data.Entity.DbSet<TimeReminder.Models.Classes.TimeReminderUserReminder> TimeReminderUserReminders { get; set; }
    }
}
